/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package firebase.firestore;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.json.JSONException;
import org.json.JSONObject;

import android.support.annotation.NonNull;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QuerySnapshot;

@Kroll.module(name = "Firestore", id = "firebase.firestore")
public class FirestoreModule extends KrollModule {

	// Standard Debugging variables
	public static final String LCAT = "FirestoreModule";
	public static FirebaseFirestore db;
	
	// You can define constants with @Kroll.constant, for example:
	@Kroll.constant
	public static final int TYPE_BOOLEAN = 0;
	@Kroll.constant
	public static final int TYPE_STRING = 1;
	@Kroll.constant
	public static final int TYPE_INT = 2;
	@Kroll.constant
	public static final int TYPE_FLOAT = 3;
	@Kroll.constant
	public static final int TYPE_DOUBLE = 4;
	@Kroll.constant
	public static final int TYPE_LONG = 5;

	public FirestoreModule() {
		super();
		db = FirebaseFirestore.getInstance();
	}
    
	public static FirebaseFirestore getDb() {
		return db;
	}
    
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	

	
}
